on:
  push:
    branches:
      - 'main'
permissions:
  id-token: write
  security-events: write
  actions: read
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::ACCOUNT_ID:role/CodeGuruSecurityGitHubAccessRole
          aws-region: AWS_REGION
          role-session-name: GitHubActionScript
      
      - name: Run CodeGuru Security Scan
        uses: aws-actions/codeguru-security@v1
        with:
          source_path: .
          aws_region: us-east-1
          fail_on_severity: Critical
      
      - name: Print Findings
        run: |
          ls -l
          cat codeguru-security-results.sarif.json
      
      - name: Upload Result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeguru-security-results.sarif.json
